name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0541c061b2b0f99761ef0c6e11291767fb126110bbe9ae82511044e709cf0a00"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1-beta.3"

[options]
acceptable-game-versions = ["1.20.1"]
