name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "6.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "180322893f6a0551e7eb5bb8d198f19bf2895ef68842062d81799561aa3b7872"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
