name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "6.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37697f2b6cd39995d979d67236813a57312ff460f563dac8fc687158f69e235e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
