name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "8.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04f4ceb14ea39796412a63c17be995ab283c18f8eb55e4a76996010cdbc9d1a4"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
