name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1141c8b954108a994efa95ac309d03389a361011af389fddcb6659b92dafc251"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
