name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "7.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7fc7e87b6d4c0776ddd7f54c1761ddbfaf8330ea86f8a9eadff5f81f2e4af00"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
