name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba54785ca087b68dfdabe609601bfdb73bf9ba92a2744075b1eda1e77b82f557"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
