name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "6.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "095d036a278ce556085dfcb71072be2ea9a239232d554508979cb4ba4e60ab60"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
