name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "5.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0bfbe044d8d377956a10c3632edb1d7a349385af91ad5ff7d249119aa3bcd3d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
