name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e3ff528fc5dd1f5c8809aae3f42adf9105760a8b9a48e6ccc436e08a47c3036"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
