name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1cfd8d400a80eab01c6c77e122998624bb91c76d57a6dc3de36569358a19679"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
