name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49dfc973078ff9ca5fcc486a4cbb1b2af17507ae092ea94c602deba0fad3fb2e"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
