name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbaf91d6e6d434e7ffd4c87a4e41bd30898d178d7350234b405aae1662885d77"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
