name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "6.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "745e75f35931f3508bbb487fe96f289a6b560e12d2e142420931d25917e08067"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
