name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdc7ba84461999d781a2dec913a8ad57a386bdcdabb96cbe4ccdc3e4a175f2d0"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
