name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f649f9bd447a29fac288dcb4c7850f81caf48467c979f5a8cad1e42be2195ad"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
