name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "9.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ef1ca4fc9a2ff3dc2b4e8914633cfc0b8aa93022e9ae71da917effab32a0179"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
