name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06c749f3801cb8d30be6fe42ae91e982fe6110b54754aebb66ba692a1de0ab40"

[versions]
minecraft = "1.20"
quilt = "0.19.1-beta.1"
