name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "9.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26e9a77b7519877218e8fb00ed73bc8b5e819ea9cc77d7b1d23400ba5ff0b3af"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
