name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "6.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bf39cf24767be5e6fcef868d8795d01f3f668af815b22f390170a4a0a4763a3"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
