name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdf7c8af53231b0a18a3c57ad1e3db97242193cff84271e3ebde8ac7da029497"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
