name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "9.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c731f7ef556af9e84806785ec6166ca4f7870cfeedb4014ba85f9dd775a4525"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
