name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "104a1ef93a8caa957727cecf8acfd7f10b4f474039ffda33a3bf8183d267cd13"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
