name = "Blumewmew's Stream Modpack"
author = "blumewmew"
version = "7.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a80cd291ab2c6eddb72fd12cb5321d2431afc317e64031701bf56f0081fab886"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
